# constants.py - 상수 정의

# 가속도 제한값 (기본값)
DEFAULT_MAX_ACCELERATION = 3.5  # m/s²
DEFAULT_MAX_DECELERATION = -7.85  # m/s²

# UI 설정
DEFAULT_WINDOW_WIDTH = 1143
DEFAULT_WINDOW_HEIGHT = 600
DEFAULT_GRAPH_WIDTH = 1000
DEFAULT_GRAPH_HEIGHT = 600

# 테이블 설정
MIN_SEGMENTS = 1
DEFAULT_SEGMENTS = 2
DEFAULT_FPS = 30.0

# 파일 형식
SUPPORTED_CSV_EXTENSIONS = ['.csv']
PROJECT_FILE_EXTENSION = '.json'
IMAGE_EXTENSIONS = ['.png', '.svg']

# 색상 설정
ACCELERATION_VALID_COLOR = 'green'
ACCELERATION_INVALID_COLOR = 'red'
OPTIMIZATION_VELOCITY_COLOR = 'green'
VIDEO_ANALYSIS_VELOCITY_COLOR = 'orange'
GROUND_TRUTH_VELOCITY_COLOR = 'deeppink'

# 그래프 설정
GRAPH_DPI = 100
POINT_SIZE = 8
LINE_WIDTH = 2

# 테이블 색상
USER_INPUT_COLOR = "#E2EFDA"
AUTO_CALCULATION_COLOR = "#FCE4D6"
PC_CRASH_INTEGRATION_COLOR = "#FFF2CC"